name = "TetherModels"
uuid = "88de02d8-15ab-452a-b040-19ff22324429"
authors = ["AndreaBertozzi <a.bertozzi@student.tudelft.nl> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
